name = "textcat-api"
main = "src/index.ts"
send_metrics = false
compatibility_date = "2023-10-25"

kv_namespaces = [{ binding = "textcat", id = "858f4ac85482462a8312e08ad8d58f20", preview_id = "d1161103085041369ce78b5d0b9a5156" }]
